## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"
title = "Barn Dance Party"
copyright = "2024"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"

cleanDestinationDir = "true"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
description = "Southern California callers and DJs for your party, community, barn dance, square dance, or whatever the occasion!"
#logo = "images/banner.jpg"
favicon = true

[Params.asset]
fontawesome_css = ["css/fontawesome-all.min.css"]
fontawesome_js = []
